
version: "2"
services:
  app:
    container_name: app
    build: .
    volumes:
      - ./:/root/hoge/
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
    command: node app.js
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./db:/root/hoge/db
    ports:
      - "27017:27017"
