
version: "2"
services:
  app:
    container_name: "app"
    depends_on:
    - mongo
    build: .
    volumes:
      - ./:/root/hoge/
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
    command: node app.js
  mongo:
    image: mongo
    container_name: "mongo"
    volumes:
      - ./db:/root/hoge/db
    ports:
      - "27017:27017"
